# -*- conf -*-

[main]
# shell=/bin/bash --noprofile
# shell=/home/linuxbrew/.linuxbrew/bin/zsh
shell=/usr/bin/env zsh
login-shell=yes
term=foot
font=Hack Nerd Font:size=12, JetBrains Mono:size=12, DejaVu Sans Mono:size=12, Noto Color Emoji:size=12
font-size-adjustment=0.5
pad=10x10 center-when-maximized-and-fullscreen
initial-window-size-chars=120x34
initial-window-mode=windowed
resize-by-cells=yes
resize-keep-grid=yes
resize-delay-ms=80
dpi-aware=no
box-drawings-uses-font-glyphs=no
bold-text-in-bright=no
selection-target=clipboard

[security]
osc52=enabled

[bell]
system=no
urgent=no
notify=no
visual=no

[scrollback]
lines=10000
multiplier=3.0
indicator-position=relative
indicator-format=" %p "

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=url-mode

[cursor]
style=beam
blink=yes
blink-rate=500
beam-thickness=1.5

[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes

[colors]
alpha=0.96
alpha-mode=default
background=282a36
foreground=f8f8f2
flash=f1fa8c
flash-alpha=0.35

regular0=21222c
regular1=ff5555
regular2=50fa7b
regular3=f1fa8c
regular4=bd93f9
regular5=ff79c6
regular6=8be9fd
regular7=f8f8f2

bright0=6272a4
bright1=ff6e6e
bright2=69ff94
bright3=ffffa5
bright4=d6acff
bright5=ff92df
bright6=a4ffff
bright7=ffffff

selection-foreground=f8f8f2
selection-background=44475a
jump-labels=282a36 f1fa8c
scrollback-indicator=282a36 bd93f9
search-box-no-match=282a36 ff5555
search-box-match=282a36 f1fa8c
urls=8be9fd

[csd]
preferred=server
size=28
color=f8f8f2
button-color=282a36
button-minimize-color=8be9fd
button-maximize-color=50fa7b
button-close-color=ff5555
border-width=0

[key-bindings]
scrollback-up-page=Shift+Page_Up Shift+KP_Page_Up
scrollback-down-page=Shift+Page_Down Shift+KP_Page_Down
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
primary-paste=Shift+Insert
search-start=Control+Shift+f
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
spawn-terminal=Control+Shift+n
fullscreen=F11
show-urls-launch=Control+Shift+u
show-urls-copy=Control+Shift+y
unicode-input=Control+Shift+i
color-theme-toggle=none

[search-bindings]
cancel=Control+g Control+c Escape
commit=Return KP_Enter
find-prev=Control+r
find-next=Control+s
cursor-left=Left Control+b
cursor-right=Right Control+f
cursor-home=Home Control+a
cursor-end=End Control+e
delete-prev=BackSpace
delete-next=Delete
delete-to-start=Control+u
delete-to-end=Control+k
clipboard-paste=Control+v Control+Shift+v Control+y XF86Paste

[url-bindings]
cancel=Control+g Control+c Control+d Escape
toggle-url-visible=t

[mouse-bindings]
scrollback-up-mouse=BTN_WHEEL_BACK
scrollback-down-mouse=BTN_WHEEL_FORWARD
font-increase=Control+BTN_WHEEL_BACK
font-decrease=Control+BTN_WHEEL_FORWARD
selection-override-modifiers=Shift
primary-paste=BTN_MIDDLE
select-begin=BTN_LEFT
select-extend=BTN_RIGHT
select-word=BTN_LEFT-2
select-row=BTN_LEFT-4
